[package]
name = "ecs-rose-offline"
version = "0.1.0"
authors = ["James Benton <james.benton2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
directories = "3.0"
encoding_rs = "0.8"
hex = "0.4"
lazy_static = "1.4.0"
legion = { version = "0.4.0", features = [] }
memmap = "0.7"
modular-bitfield = "0.11.2"
num-derive = "0.3"
num-traits = "0.2"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
sha2 = "0.9"
tempfile = "3.2.0"
tokio = { version = "1.4.0", features = ["full"] }
crossbeam-channel = "0.5.0"
scopeguard = "1.1.0"
async-trait = "0.1.48"
rand = "0.8.3"
