[package]
name = "rose-game-common"
version = "0.1.0"
authors = ["James Benton <james.benton2@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { version = "0.8.0", default-features = false }
bitvec = { version = "1.0", features = ["serde"] }
enum-map = { version = "2.0", features = ["serde"] }
log = "0.4"
rose-data = { path = "../rose-data" }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
